spring.application.name=pulsedesk-backend
spring.profiles.active=local
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.urls[0].name=Production
springdoc.swagger-ui.urls[0].url=https://pulsedesk-backend-production.up.railway.app/v3/api-docs